(define balance 100)

(define (withdraw amt)
  (if (>= balance amt)
      (begin (set! balance (- balance amt))
             balance)
      "Insufficient funds"))

(define new-withdraw
  (let ((balance 100))
    (lambda (amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))))

(define (make-account balance)
  (define (withdraw amt)
    (if (>= balance amt)
        (begin (set! balance (- balance amt))
               balance)
        "Insufficient funds"))
  (define (deposit amt)
    (if (> amt 0)
        (begin (set! balance (+ balance amt))
               balance)
        (withdraw (abs amt))))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
m))))
dispatch)